# Generated by Django 5.0.1 on 2024-01-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profiles',
            field=models.ManyToManyField(to='core.profile'),
        ),
    ]
